import apiClient from './apiClient.js';
import { userEndpoints } from './userEndpoints.js';

const unwrap = (response) => response.data?.data ?? response.data;
export const userAdditionalService = Object.freeze({
  listCities: async () => unwrap(await apiClient.get(userEndpoints.locations.cities)),
  getCity: async (id) => unwrap(await apiClient.get(userEndpoints.locations.city(id))),
  listAreas: async () => unwrap(await apiClient.get(userEndpoints.locations.areas)),
  getArea: async (id) => unwrap(await apiClient.get(userEndpoints.locations.area(id))),
  listAreasByCity: async (cityId) => unwrap(await apiClient.get(userEndpoints.locations.areasByCity(cityId))),
  addFavorite: async (bookingId) => unwrap(await apiClient.post(userEndpoints.favorites.add(bookingId))),
  listFavorites: async () => unwrap(await apiClient.get(userEndpoints.favorites.list)),
  addWallet: async (payload) => unwrap(await apiClient.post(userEndpoints.wallet.add, payload)),
  removeWallet: async (payload) => unwrap(await apiClient.post(userEndpoints.wallet.remove, payload)),
  getWallet: async () => unwrap(await apiClient.get(userEndpoints.wallet.get)),
  walletTransactions: async () => unwrap(await apiClient.get(userEndpoints.wallet.transactions)),
  walletCredits: async () => unwrap(await apiClient.get(userEndpoints.wallet.creditTransactions)),
  walletDebits: async () => unwrap(await apiClient.get(userEndpoints.wallet.debitTransactions)),
  testimonials: async () => unwrap(await apiClient.get(userEndpoints.testimonials.list)),
  testimonial: async (id) => unwrap(await apiClient.get(userEndpoints.testimonials.getById(id))),
  createRating: async (payload) => unwrap(await apiClient.post(userEndpoints.ratings.create, payload)),
  listRatings: async () => unwrap(await apiClient.get(userEndpoints.ratings.list)),
  listUserRatings: async (type) => unwrap(await apiClient.get(userEndpoints.ratings.listForUser, { params: type ? { type } : undefined })),
  getRating: async (id) => unwrap(await apiClient.get(userEndpoints.ratings.getById(id))),
  rateMainCategory: async (payload) => unwrap(await apiClient.post(userEndpoints.ratings.rateMainCategory, payload)),
  createTicket: async (payload) => unwrap(await apiClient.post(userEndpoints.tickets.create, payload)),
  listTickets: async () => unwrap(await apiClient.get(userEndpoints.tickets.list)),
  getTicket: async (id) => unwrap(await apiClient.get(userEndpoints.tickets.getById(id))),
  replyTicket: async (id, payload) => unwrap(await apiClient.put(userEndpoints.tickets.reply(id), payload)),
  notifications: async () => unwrap(await apiClient.get(userEndpoints.notifications.list)),
  notificationsForUser: async (id) => unwrap(await apiClient.get(userEndpoints.notifications.forUser(id))),
  markNotificationRead: async (id) => unwrap(await apiClient.put(userEndpoints.notifications.markAsRead(id))),
  markAllNotificationsRead: async () => unwrap(await apiClient.put(userEndpoints.notifications.markAllAsRead)),
  plans: async () => unwrap(await apiClient.get(userEndpoints.plans.list)),
  plan: async (id) => unwrap(await apiClient.get(userEndpoints.plans.getById(id))),
  purchasePlan: async (payload) => unwrap(await apiClient.post(userEndpoints.plans.purchase, payload)),
  userPlans: async () => unwrap(await apiClient.get(userEndpoints.plans.userPlans)),
  userPlan: async (id) => unwrap(await apiClient.get(userEndpoints.plans.userPlan(id))),
  updateUserPlan: async (id, payload) => unwrap(await apiClient.put(userEndpoints.plans.updateUserPlan(id), payload)),
  deleteUserPlan: async (id) => unwrap(await apiClient.delete(userEndpoints.plans.removeUserPlan(id))),
  cards: async () => unwrap(await apiClient.get(userEndpoints.cards.list)),
  addCard: async (payload) => unwrap(await apiClient.post(userEndpoints.cards.create, payload)),
  updateCard: async (id, payload) => unwrap(await apiClient.put(userEndpoints.cards.update(id), payload)),
  deleteCard: async (id) => unwrap(await apiClient.delete(userEndpoints.cards.remove(id))),
});
